# Generated by Django 4.2 on 2024-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=3000)),
                ('roast_profile', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
