# Generated by Django 4.2 on 2024-04-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamoApp', '0004_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration',
        ),
    ]
